{
  "MonsterType": {
    "1": "Demon",
    "2": "Beast",
    "3": "Human",
    "4": "Undead"
  },
  "Element": {
    "0": "Physical",
    "1": "Fire",
    "2": "Lightning",
    "3": "Cold",
    "4": "Poison",
    "5": "Arcane",
    "6": "Holy"
  },
  "Resource": {
    "0": "Mana",
    "1": "Arcanum",
    "2": "Fury",
    "3": "Spirit",
    "5": "Hatred",
    "6": "Discipline",
    "7": "Faith"
  },
  "ResourceX": {
    "witchdoctor": "Mana",
    "wizard": "Arcane Power",
    "barbarian": "Fury",
    "monk": "Spirit",
    "demonhunter": "Hatred",
    "crusader": "Wrath"
  },
  "AffixFix": {
    "9": [
      [125, 1],
      [163, 5],
      [670, 7],
      [1086, 8],
      [1176, 9]
    ],
    "6": [
      [125, 1],
      [164, 4],
      [671, 6]
    ],
    "5": [
      [165, 3],
      [672, 5]
    ],
    "0": [],
    "-1": [
      [678, -1]
    ],
    "-11": [
      [135, -1],
      [338, -3],
      [687, -10],
      [1064, -11]
    ]
  },
  "Affixes": {
    "10": "Strength_Item",
    "11": "Dexterity_Item",
    "12": "Intelligence_Item",
    "13": "Vitality_Item",
    "50": "Gold_Find",
    "60": "Magic_Find",
    "71": "Resource_Set_Point_Bonus#{Resource}",
    "73": "Spending_Resource_Heals_Percent#{Resource}",
    "77": "Experience_Bonus",
    "78": "Experience_Bonus_Percent",
    "82": "Health_Globe_Bonus_Chance",
    "86": "Health_Globe_Bonus_Health",
    "93": "Resistance#{Element}",
    "96": "Resistance_All",
    "126": "Hitpoints_Regen_Per_Second",
    "134": "Hitpoints_Max_Percent_Bonus_Item",
    "150": "Resource_Max_Bonus#{Resource}",
    "156": "Resource_Regen_Per_Second#{Resource}",
    "168": "Movement_Speed",
    "192": "Attacks_Per_Second_Item_Percent",
    "200": "Attacks_Per_Second_Percent",
    "207": "Power_Cooldown_Reduction_Percent_All",
    "209": "Damage#{Element} (pair)$2",
    "211": "Damage#{Element} (pair)$0",
    "219": "Damage#{Element} (pair)$2",
    "226": "Damage_Weapon_Bonus_Delta#{Element}",
    "227": "Damage#{Element} (pair)$2",
    "228": "Damage#{Element} (pair)$0",
    "234": "Damage_Weapon_Bonus_Min#{Element}",
    "235": "Damage#{Element} (pair)$0",
    "237": "Damage_Percent",
    "238": "Damage_Weapon_Percent_Bonus",
    "240": "Damage_Type_Percent_Bonus#{Element}",
    "241": "Damage_Dealt_Percent_Bonus#{Element}",
    "245": "Critical_Chance",
    "250": "Crit_Damage_Percent",
    "260": "Block_Chance_Bonus_Item",
    "331": "Thorns_Fixed#{Element}",
    "335": "Steal_Health_Percent",
    "337": "Resource_On_Hit#{Resource}",
    "340": "Resource_On_Kill#{Resource}",
    "341": "Resource_On_Crit#{Resource}",
    "342": "Hitpoints_On_Hit",
    "343": "Hitpoints_On_Kill",
    "367": "Amplify_Damage_Type_Percent#{Element}",
    "381": "@Sockets ({VALUE})",
    "682": "Resistance_Stun",
    "684": "Resistance_Root",
    "686": "Resistance_Freeze",
    "688": "Resistance_StunRootFreeze",
    "689": "CrowdControl_Reduction",
    "722": "Resource_Cost_Reduction_Percent_All",
    "1053": "Gold_PickUp_Radius",
    "1094": "On_Hit_Fear_Proc_Chance",
    "1095": "On_Hit_Stun_Proc_Chance",
    "1096": "On_Hit_Blind_Proc_Chance",
    "1097": "On_Hit_Freeze_Proc_Chance",
    "1098": "On_Hit_Chill_Proc_Chance",
    "1099": "On_Hit_Slow_Proc_Chance",
    "1100": "On_Hit_Immobilize_Proc_Chance",
    "1101": "On_Hit_Knockback_Proc_Chance",
    "1105": "Damage_Percent_Reduction_From_Ranged",
    "1106": "Damage_Percent_Reduction_From_Melee",
    "1108": "Damage_Percent_Reduction_From_Elites",
    "1109": "Damage_Type_Percent_Reduction#{Element}",
    "1110": "Damage_Percent_Bonus_Vs_Monster_Type#{MonsterType}",
    "1111": "Damage_Percent_Bonus_Vs_Elites",
    "1117": "Weapon_On_Hit_Fear_Proc_Chance",
    "1118": "Weapon_On_Hit_Stun_Proc_Chance",
    "1119": "Weapon_On_Hit_Blind_Proc_Chance",
    "1120": "Weapon_On_Hit_Freeze_Proc_Chance",
    "1121": "Weapon_On_Hit_Chill_Proc_Chance",
    "1122": "Weapon_On_Hit_Slow_Proc_Chance",
    "1123": "Weapon_On_Hit_Immobilize_Proc_Chance",
    "1124": "Weapon_On_Hit_Knockback_Proc_Chance",
    "1125": "Weapon_On_Hit_Bleed_Proc_Chance$1",
    "1126": "Weapon_On_Hit_Bleed_Proc_Chance$2",
    "1127": "Weapon_On_Hit_Bleed_Proc_Chance$3",
    "1128": "Weapon_On_Hit_Percent_Bleed_Proc_Chance$1",
    "1129": "Weapon_On_Hit_Percent_Bleed_Proc_Chance$2",
    "1130": "Weapon_On_Hit_Percent_Bleed_Proc_Chance$3",
    "1173": "&Power_Damage_Percent_Bonus",
    "1175": "&Power_Resource_Reduction",
    "1177": "&Power_Cooldown_Reduction",
    "1185": "Strength_Item",
    "1186": "Dexterity_Item",
    "1187": "Intelligence_Item",
    "1188": "Vitality_Item",
    "1189": "Item_Level_Requirement_Reduction",
    "1190": "Item_Level_Requirement_Override",
    "1192": "Item_Indestructible",
    "1270": "{Power}",
    "1297": "Item_Is_BOE",
    "1331": "Splash_Damage_Effect_Percent",
    "1332": "Crushing_Blow_Chance",
    "1335": "Set_Item_Discount"
  },
  "Secondary": {
    "1053": "Gold_PickUp_Radius",
    "1094": "On_Hit_Fear_Proc_Chance",
    "1095": "On_Hit_Stun_Proc_Chance",
    "1096": "On_Hit_Blind_Proc_Chance",
    "1097": "On_Hit_Freeze_Proc_Chance",
    "1098": "On_Hit_Chill_Proc_Chance",
    "1099": "On_Hit_Slow_Proc_Chance",
    "1100": "On_Hit_Immobilize_Proc_Chance",
    "1101": "On_Hit_Knockback_Proc_Chance",
    "1105": "Damage_Percent_Reduction_From_Ranged",
    "1106": "Damage_Percent_Reduction_From_Melee",
    "1110": "Damage_Percent_Bonus_Vs_Monster_Type#{MonsterType}",
    "1117": "Weapon_On_Hit_Fear_Proc_Chance",
    "1118": "Weapon_On_Hit_Stun_Proc_Chance",
    "1119": "Weapon_On_Hit_Blind_Proc_Chance",
    "1120": "Weapon_On_Hit_Freeze_Proc_Chance",
    "1121": "Weapon_On_Hit_Chill_Proc_Chance",
    "1122": "Weapon_On_Hit_Slow_Proc_Chance",
    "1123": "Weapon_On_Hit_Immobilize_Proc_Chance",
    "1124": "Weapon_On_Hit_Knockback_Proc_Chance",
    "1125": "Weapon_On_Hit_Bleed_Proc_Chance$1",
    "1126": "Weapon_On_Hit_Bleed_Proc_Chance$2",
    "1127": "Weapon_On_Hit_Bleed_Proc_Chance$3",
    "1128": "Weapon_On_Hit_Percent_Bleed_Proc_Chance$1",
    "1129": "Weapon_On_Hit_Percent_Bleed_Proc_Chance$2",
    "1130": "Weapon_On_Hit_Percent_Bleed_Proc_Chance$3",
    "1189": "Item_Level_Requirement_Reduction",
    "1190": "Item_Level_Requirement_Override",
    "1192": "Item_Indestructible",
    "1270": "{Power}",
    "1297": "Item_Is_BOE",
    "1335": "Set_Item_Discount",
    "150": "Resource_Max_Bonus#{Resource}",
    "168": "Movement_Speed",
    "331": "Thorns_Fixed#{Element}",
    "343": "Hitpoints_On_Kill",
    "50": "Gold_Find",
    "60": "Magic_Find",
    "682": "Resistance_Stun",
    "684": "Resistance_Root",
    "686": "Resistance_Freeze",
    "688": "Resistance_StunRootFreeze",
    "689": "CrowdControl_Reduction",
    "77": "Experience_Bonus",
    "78": "Experience_Bonus_Percent",
    "86": "Health_Globe_Bonus_Health",
    "93": "Resistance#{Element}"
  }
}